hw04
IhorHrytsenko/Hrytsenko-nodejs-homework pull request #2
Opened 2022-01-11 17:30 UTC by IhorHrytsenko

2022-01-11 20:03 UTC, KirillKulakow commented on app.js
> +=======
что это? я так понял не решенные конфликты

2022-01-11 20:03 UTC, KirillKulakow commented on middlewares/guard.js
> +  console.log(
???

2022-01-11 20:03 UTC, KirillKulakow commented on app.js
> +>>>>>>> Stashed changes
???

2022-01-11 20:04 UTC, KirillKulakow commented on app.js
> +<<<<<<< Updated upstream
???

2022-01-11 20:12 UTC, KirillKulakow commented on package.json
> +<<<<<<< Updated upstream
???

2022-01-11 20:12 UTC, KirillKulakow commented on package.json
> +<<<<<<< Updated upstream
???

2022-01-11 20:14 UTC, KirillKulakow requested changes
Need fix

2022-01-12 16:49 UTC, IhorHrytsenko commented on app.js
> +=======
Странно, при создании ветки и пуше мне ГИТ сказал что все хорошо и нет конфликтов, я даже удивился. Ок, поправим.

2022-01-24 19:21 UTC, closed without merging